spring:
  datasource:
    url: jdbc:postgresql://postgres:mWGAGwsIrhfiG6zx30ou@containers-us-west-123.railway.app:7944/railway
    username: postgres
    password: mWGAGwsIrhfiG6zx30ou
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always